from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    ListView, CreateView, UpdateView, DeleteView, TemplateView, View
)
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.http import require_GET
from django.db import transaction, models
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from decimal import Decimal, InvalidOperation
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth import get_user_model
from django.db.models import Avg, Count, Sum
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.views.decorators.http import require_http_methods
import threading
import os
import json
from realsproj.forms import (
    ProductsForm,
    RawMaterialsForm,
    SalesForm,
    ExpensesForm,
    SalesExpensesForm,
    ProductBatchForm,
    ProductInventoryForm,
    RawMaterialBatchForm,
    RawMaterialInventoryForm,
    ProductTypesForm,
    ProductVariantsForm,
    SizesForm,
    SizeUnitsForm,
    UnitPricesForm,
    SrpPricesForm,
    BulkProductBatchForm,
    BulkRawMaterialBatchForm,
    CustomUserCreationForm,
    WithdrawEditForm,
    UserEditForm
)

from realsproj.models import (
    Products,
    RawMaterials,
    HistoryLog,
    HistoryLogTypes,
    Sales,
    Expenses,
    ProductBatches,
    ProductInventory,
    RawMaterialBatches,
    RawMaterialInventory,
    ProductTypes,
    ProductVariants,
    Sizes,
    SizeUnits,
    UnitPrices,
    SrpPrices,
    Withdrawals,
    Notifications,
    AuthUser,
    StockChanges,
    SalesSummary,
    ExpensesSummary,
    Discounts,
    UserActivity,
    PriceHistory
)

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models.functions import TruncMonth, TruncDay
from django.db.models.functions import Cast
from django.contrib.auth.models import User
from django.http import HttpResponse
import csv
from datetime import datetime, timedelta, date
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver
from django.utils import timezone
from django.db.models import Q, F, CharField
import re

from realsproj.views.helpers import (
    get_or_create_auth_user,
    create_history_log,
    mask_email,
    get_client_ip,
    get_device_fingerprint,
    get_device_info,
)
from realsproj.views.products import (
    ProductsList,
    product_scan_phone,
    check_barcode_availability,
    ProductArchiveView,
    ArchivedProductsListView,
    ProductUnarchiveView,
    ProductArchiveOldView,
    product_bulk_delete,
    product_bulk_archive,
    product_bulk_restore,
    ProductCreateView,
    ProductsUpdateView,
    delete_old_product_photo_on_change,
    delete_product_photo_on_delete,
    ProductsDeleteView,
    ProductBatchList,
    ProductBatchCreateView,
    ProductBatchUpdateView,
    ProductBatchDeleteView,
    ProductBatchArchiveView,
    ArchivedProductBatchListView,
    ProductBatchUnarchiveView,
    ProductBatchArchiveOldView,
    product_batch_bulk_delete,
    product_batch_bulk_archive,
    product_batch_bulk_restore,
    ProductInventoryList,
    ProductVariantCreateView,
    SizesCreateView,
    SizeUnitsCreateView,
    UnitPricesCreateView,
    SrpPricesCreateView,
    ProductAttributesView,
    ProductTypeAddView,
    ProductTypeEditView,
    ProductTypeDeleteView,
    ProductVariantAddView,
    ProductVariantEditView,
    ProductVariantDeleteView,
    SizeAddView,
    SizeEditView,
    SizeDeleteView,
    SizeUnitAddView,
    SizeUnitEditView,
    SizeUnitDeleteView,
    UnitPriceAddView,
    UnitPriceEditView,
    UnitPriceDeleteView,
    SrpPriceAddView,
    SrpPriceEditView,
    SrpPriceDeleteView,
    BulkProductBatchCreateView,
    export_product_inventory,
    PriceHistoryList,
    export_price_history,
    check_product_batches,
)
from realsproj.views.materials import (
    RawMaterialsList,
    RawMaterialArchiveView,
    RawMaterialArchiveOldView,
    rawmaterial_bulk_delete,
    rawmaterial_bulk_archive,
    rawmaterial_bulk_restore,
    ArchivedRawMaterialsListView,
    ArchivedPackagingMaterialsListView,
    RawMaterialUnarchiveView,
    RawMaterialsCreateView,
    RawMaterialsUpdateView,
    RawMaterialsDeleteView,
    CategoryFilteredRawMaterialsList,
    CategoryRawMaterialsCreateView,
    CategoryRawMaterialsUpdateView,
    PackagingMaterialsList,
    PackagingMaterialsCreateView,
    PackagingMaterialsUpdateView,
    RawMaterialBatchList,
    RawMaterialBatchCreateView,
    RawMaterialBatchUpdateView,
    RawMaterialBatchDeleteView,
    RawMaterialBatchArchiveView,
    ArchivedRawMaterialBatchListView,
    RawMaterialBatchUnarchiveView,
    RawMaterialBatchBulkRestoreView,
    RawMaterialBatchArchiveOldView,
    rawmaterial_batch_bulk_delete,
    rawmaterial_batch_bulk_archive,
    RawMaterialInventoryList,
    export_rawmaterial_inventory,
    BulkRawMaterialBatchCreateView,
    check_rawmaterial_batches,
    check_rawmaterial_duplicates,
)
from realsproj.views.sales import (
    sales_vs_expenses,
    revenue_change_api,
    SaleArchiveView,
    SaleArchiveOldView,
    ArchivedSalesListView,
    ArchivedSalesExpensesCombinedView,
    SaleUnarchiveView,
    sales_bulk_delete,
    sales_bulk_archive,
    SaleBulkRestoreView,
    SaleBulkDeleteView,
    SalesExpensesList,
    SalesCreateView,
    SalesUpdateView,
    SalesDeleteView,
    WithdrawalOrderDetailView,
    WithdrawalOrderUpdatePaymentView,
    ExpenseArchiveView,
    ExpenseArchiveOldView,
    expenses_bulk_delete,
    expenses_bulk_archive,
    ArchivedExpensesListView,
    ExpenseUnarchiveView,
    ExpenseBulkRestoreView,
    ExpensesCreateView,
    ExpensesUpdateView,
    ExpensesDeleteView,
    SalesExpensesCreateView,
    get_total_revenue,
    export_sales,
    export_expenses,
    check_sales_duplicates,
    check_expenses_duplicates,
)
from realsproj.views.withdrawals import (
    WithdrawSuccessView,
    export_withdrawals,
    WithdrawItemView,
    WithdrawalsArchiveView,
    ArchivedWithdrawalsListView,
    WithdrawalsUnarchiveView,
    WithdrawalBulkRestoreView,
    WithdrawalsArchiveOldView,
    withdrawals_bulk_delete,
    withdrawals_bulk_archive,
    WithdrawUpdateView,
    WithdrawDeleteView,
    WithdrawalGroupArchiveView,
    WithdrawalGroupDeleteView,
    WithdrawalGroupEditView,
    get_stock,
    StockChangesList,
    export_stock_changes,
    StockChangesArchiveView,
    stock_changes_bulk_archive,
    ArchivedStockChangesListView,
    StockChangesUnarchiveView,
    StockChangesBulkRestoreView,
    StockChangesArchiveOldView,
    check_withdrawal_duplicates,
)
from realsproj.views.users import (
    profile_view,
    download_my_data,
    login_view,
    register,
    user_management,
    approve_user,
    reject_user,
    send_role_change_email_async,
    toggle_user_role,
    create_admin_user,
    send_deactivation_email_async,
    send_reactivation_email_async,
    deactivate_user,
    reactivate_user,
    delete_user,
    edit_profile,
    UserActivityList,
    check_account_status,
    clear_deactivation_flag,
    setup_2fa,
    send_login_notification,
    disable_2fa,
    delete_account,
    direct_password_reset,
    verify_current_password,
    privacy_policy,
    terms_of_use,
)
from realsproj.views.reports import (
    HomePageView,
    monthly_report,
    monthly_report_export,
    HistoryLogList,
    NotificationsList,
    best_sellers_api,
    mark_notification_read,
    database_backup,
    BestSellerProductsView,
    export_bestseller_report,
    financial_loss,
    financial_loss_export,
)