# Generated by Django 5.2.14 on 2026-05-27 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('AMOUNT', 'Fixed Amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'discounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'expenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpensesSummary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'expenses_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialLoss',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=50)),
                ('item_id', models.BigIntegerField()),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loss_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=50)),
                ('loss_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'financial_loss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.BigIntegerField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'history_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryLogTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'history_log_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('required_otp', models.BooleanField(default=False)),
                ('is_trusted_device', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'login_attempts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=12)),
                ('item_id', models.BigIntegerField()),
                ('notification_type', models.CharField(max_length=20)),
                ('notification_timestamp', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_type', models.CharField(choices=[('UNIT', 'Unit Price'), ('SRP', 'SRP')], max_length=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'price_history',
                'ordering': ['-changed_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductBatches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.IntegerField()),
                ('original_quantity', models.IntegerField(blank=True, null=True)),
                ('manufactured_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'product_batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_photos/')),
                ('is_archived', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('product_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_variants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterialBatches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_date', models.DateField(default=django.utils.timezone.localdate)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_material_batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_archived', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'raw_materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'sales_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size_label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sizes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SizeUnits',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'size_units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SrpPrices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('srp_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'srp_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockChanges',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=12)),
                ('item_id', models.BigIntegerField()),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.TextField()),
                ('date', models.DateTimeField()),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'stock_changes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'trusted_devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitPrices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'unit_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User2FASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('backup_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_2fa_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_otp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('RAW_MATERIAL', 'Raw Material')], max_length=12)),
                ('item_id', models.BigIntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('SOLD', 'Sold'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('REPLACEMENT_FOR_RETURNED', 'Replacement for Returned Items'), ('OTHERS', 'Others')], max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sales_channel', models.CharField(blank=True, choices=[('ORDER', 'Order'), ('CONSIGNMENT', 'Consignment'), ('RESELLER', 'Reseller'), ('PHYSICAL_STORE', 'Physical Store')], max_length=20, null=True)),
                ('price_type', models.CharField(blank=True, choices=[('UNIT', 'Unit Price'), ('SRP', 'SRP')], max_length=10, null=True)),
                ('custom_discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial Payment')], default='PAID', max_length=20, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_group_id', models.BigIntegerField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, db_index=True, help_text='Unique receipt/reference number for this sale', max_length=50, null=True, unique=True)),
                ('actual_unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price (unit or SRP) at time of sale', max_digits=10, null=True)),
                ('actual_discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage applied', max_digits=5, null=True)),
                ('actual_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount applied', max_digits=10, null=True)),
                ('final_price_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Final price per unit after discount', max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount (quantity × final_price_per_unit)', max_digits=10, null=True)),
            ],
            options={
                'db_table': 'withdrawals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='realsproj.products')),
                ('total_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restock_threshold', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'product_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterialInventory',
            fields=[
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='realsproj.rawmaterials')),
                ('total_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'raw_material_inventory',
                'managed': False,
            },
        ),
    ]
