# Generated by Django 5.0.6 on 2025-11-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realsproj', '0015_update_withdrawal_reason_constraint'),
    ]

    operations = [
    ]
